[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alok8663/Numpy/blob/main/Numpy2.ipynb)


# Arithmetic Functions

In [1]:
import numpy as np

var=np.array([1,5,423,89,4])
print(np.min(var),"  ",np.argmin(var))
print(np.max(var),"  ",np.argmax(var))

1    0
423    2


In [2]:
var1=np.array([[3,89,4],[5,7,8]])
print(np.max(var1,axis=0))
print(np.max(var1,axis=1))

[ 5 89  8]
[89  8]


In [3]:
print(np.sqrt(var))

[ 1.          2.23606798 20.5669638   9.43398113  2.        ]


In [4]:
print(np.sin(var))

[ 0.84147098 -0.95892427  0.89791441  0.86006941 -0.7568025 ]


In [5]:
print(np.cos(var))

[ 0.54030231  0.28366219 -0.44017009  0.51017704 -0.65364362]


In [6]:
print(np.cumsum(var))

[  1   6 429 518 522]


# Shaping and Reshaping in Numpy Arrays

In [7]:
arr=np.array([[1,2,3],[3,4,5]])
print(arr)
print(np.shape(arr))

[[1 2 3]
 [3 4 5]]
(2, 3)


In [8]:
arr1=np.array([[1,9,3],[3,7,5]])
print(arr1)
print(arr1.shape)

[[1 9 3]
 [3 7 5]]
(2, 3)


In [9]:
var2=np.array([1,2,3,4,5,6,7,9])
x=var2.reshape(4,2)
print(var2)
print(var2.ndim)
print(' ')
print(x)
print(x.ndim)

[1 2 3 4 5 6 7 9]
1
 
[[1 2]
 [3 4]
 [5 6]
 [7 9]]
2


In [10]:
var3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x1=var3.reshape(2,3,2)
print(x1)
print(x1.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [11]:
x2=x1.reshape(-1)
print(x2)
print(x2.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Broadcasting in Numpy Arrays

In [12]:
arr2=np.array([1,2,3])
print(arr2)
print(arr2.shape)

[1 2 3]
(3,)


In [13]:
arr3=np.array([[1],[2],[3]])
print(arr3)
print(arr3.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [14]:
print(arr2+arr3)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing

In [15]:
a=np.array([6,7,8,5,4])
print(a[3])
print(a[-3])

5
8


In [16]:
b=np.array([[4,5,6],[8,1,2]])
print(b)
print(b.ndim)
print()
print(b[1][2])
print(b[0,2])

[[4 5 6]
 [8 1 2]]
2

2
6


# Slicing

In [17]:
a=np.array([6,7,8,5,4,3,2,1])
print(a[1:4])

[7 8 5]


In [18]:
b=np.array([[4,5,6],[8,1,2]])
print(b)
print(b[1,1:])

[[4 5 6]
 [8 1 2]]
[1 2]


#Iteration

In [19]:
a=np.array([6,7,8,5,4,3,2,1])
print(a)
print()
for i in a:
  print(i)

[6 7 8 5 4 3 2 1]

6
7
8
5
4
3
2
1


In [20]:
b=np.array([[4,5,6],[8,1,2]])
print(b)
print()
for j in b:
  print(j)

[[4 5 6]
 [8 1 2]]

[4 5 6]
[8 1 2]


In [21]:
for j in b:
  for k in j:
    print(k)

4
5
6
8
1
2


In [22]:
c=np.array([[[4,5,6],[8,1,2]]])
for i in c:
  for j in i:
    for k in j:
      print(k)

4
5
6
8
1
2


In [23]:
for i in np.nditer(c):
  print(i)

4
5
6
8
1
2


In [24]:
for i,d in np.ndenumerate(c):
  print(i,d)

(0, 0, 0) 4
(0, 0, 1) 5
(0, 0, 2) 6
(0, 1, 0) 8
(0, 1, 1) 1
(0, 1, 2) 2


# Copy vs View

In [25]:
a=np.array([6,7,8,5,4,3,2,1])
co=a.copy()
print('a: ',a)
print('co: ',co)

a:  [6 7 8 5 4 3 2 1]
co:  [6 7 8 5 4 3 2 1]


In [26]:
a=np.array([6,7,8,5,4,3,2,1])
vi=a.view()
print('a: ',a)
print('view: ',vi)

a:  [6 7 8 5 4 3 2 1]
view:  [6 7 8 5 4 3 2 1]


# Join Array

In [27]:
var5=np.array([1,2,3,4])
var6=np.array([9,8,7,6])
ar=np.concatenate((var5,var6))
print(ar)

[1 2 3 4 9 8 7 6]


In [28]:
b1=np.array([[4,5,6],[8,1,2]])
print(b1)
print()
b2=np.array([[42,51,64],[83,12,21]])
print(b2)
print()
ar1=np.concatenate((b1,b2),axis=1)
print(ar1)
print()
ar2=np.concatenate((b1,b2),axis=0)
print(ar2)

[[4 5 6]
 [8 1 2]]

[[42 51 64]
 [83 12 21]]

[[ 4  5  6 42 51 64]
 [ 8  1  2 83 12 21]]

[[ 4  5  6]
 [ 8  1  2]
 [42 51 64]
 [83 12 21]]


In [29]:
b3=np.array([4,5,6])
b4=np.array([42,51,64])
ar3=np.stack((b3,b4),axis=1)
ar4=np.hstack((b3,b4)) #rows
ar5=np.vstack((b3,b4)) #columns
ar6=np.dstack((b3,b4)) #height
print(ar3)
print()
print(ar4)
print()
print(ar5)
print()
print(ar6)

[[ 4 42]
 [ 5 51]
 [ 6 64]]

[ 4  5  6 42 51 64]

[[ 4  5  6]
 [42 51 64]]

[[[ 4 42]
  [ 5 51]
  [ 6 64]]]


# Split Array

In [30]:
b4=np.array([4,5,6,7,8,9])
print(b4)
print()
ar_split=np.array_split(b4,4)
print(ar_split)
print(type(ar_split))

[4 5 6 7 8 9]

[array([4, 5]), array([6, 7]), array([8]), array([9])]
<class 'list'>
