[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alok8663/Numpy/blob/main/Numpy1.ipynb)


In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
y=np.arange(1,6)
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
%timeit [j*4 for j in range(1,5)]

723 ns ± 341 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
l=[]
for i in range(1,6):
  a=int(input("a= "))
  l.append(a)
print(np.array(l))


a= 1
a= 2
a= 3
a= 4
a= 5
[1 2 3 4 5]


In [ ]:
print(y.ndim)

1


In [ ]:
ar2=np.array([[1,2,3],[4,5,6]])
print(ar2)
print(ar2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
print(np.shape(ar2))

(2, 3)


In [ ]:
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zero Array

In [ ]:
arr1=np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [ ]:
arr2=np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


# Ones Array

In [ ]:
arr3=np.ones(4)
print(arr3)

[1. 1. 1. 1.]


In [ ]:
arr4=np.ones((2,5))
print(arr4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Creating an Empty Array

In [ ]:
arr_em=np.empty(5)
print(arr_em)

[0. 0. 0. 0. 0.]


# An array with a range of elements

In [ ]:
arr5=np.arange(1,8)
print(arr5)

[1 2 3 4 5 6 7]


# Diagonal Elements filled with 1

In [ ]:
arr_dia=np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr_dia2=np.eye(4,3)
print(arr_dia2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# Linspace

In [ ]:
arr_lin=np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


# Generating Random Numbers

## rand()

In [ ]:
a=np.random.rand(5)
print(a)

[0.70889419 0.74795697 0.13919882 0.86001556 0.33635725]


In [ ]:
b=np.random.rand(2,3)
print(b)

[[0.33104947 0.53420698 0.91464931]
 [0.41214535 0.46059721 0.44060273]]


## randn()

In [ ]:
c=np.random.randn(5)
print(c)

[ 0.25296494 -1.80140146 -0.14909299  1.13351741 -0.61829863]


In [ ]:
d=np.random.randn(2,3)
print(d)

[[ 0.2079579  -0.6863014  -0.66372614]
 [ 0.41225328  1.13229688  1.60212649]]


## ranf()

In [ ]:
var1=np.random.ranf(4)
print(var1)

[0.61080588 0.97098648 0.08580953 0.40467945]


In [ ]:
var2=np.random.ranf((4,2))
print(var2)

[[0.1356109  0.02950353]
 [0.86602798 0.83825641]
 [0.04183528 0.6270136 ]
 [0.58265969 0.69860042]]


## randint()

In [ ]:
x=np.random.randint(2,45,4)
print(x)

[26 12 31  7]


# Data Type

In [ ]:
var=np.array([4,45,23,67,3])
var.dtype

dtype('int64')

In [ ]:
var1=np.array([4,45.0,23,6.4,3])
var1.dtype

dtype('float64')

In [ ]:
var2=np.array(['a','d','frd'])
var2.dtype

dtype('<U3')

In [ ]:
var3=np.array(['a','d','frd',44,56])
var3.dtype

dtype('<U21')

In [ ]:
x=np.array([3,4,2,1],dtype=np.int8)
x.dtype
print(x)

[3 4 2 1]


In [ ]:
x1=np.array([3,4,2,1],dtype='f')
x1.dtype
print(x1)

[3. 4. 2. 1.]


In [ ]:
x2=np.array([3,4,2,1])
new=np.float32(x2)
x2.dtype
print(x2)
print(new)

[3 4 2 1]
[3. 4. 2. 1.]


In [ ]:
x3=np.array([3,4,2,1])
new_one=x3.astype(float)
print(new_one)
new_one.dtype

[3. 4. 2. 1.]


dtype('float64')

# Arithmetic Operations in Numpy Arrays

In [ ]:
var=np.array([1,2,3,4])
varadd=var+4
print(varadd)

[5 6 7 8]


In [ ]:
var1=np.array([1,2,3,4])
var2=np.array([1,1,1,3])
sum=var1+var2
print('Sum= ',sum)

Sum=  [2 3 4 7]


In [ ]:
var=np.array([1,2,3,4])
varsub=var-8
print(varsub)

[-7 -6 -5 -4]


In [ ]:
var=np.array([1,2,3,4])
varmultiply=var*8
print(varmultiply)

[ 8 16 24 32]


In [ ]:
var=np.array([1,2,3,4])
var_divide=var/8
print(var_divide)

[0.125 0.25  0.375 0.5  ]


In [ ]:
var=np.array([1,2,3,4])
var_remainder=var%4
print(var_remainder)

[1 2 3 0]


In [ ]:
var=np.array([1,2,3,4])
var_power=var**2
print(var_power)

[ 1  4  9 16]


In [ ]:
var1=np.array([1,2,3,4])
var2=np.array([1,4,1,3])
sum=np.add(var1,var2)
print('Sum= ',sum)

Sum=  [2 6 4 7]


In [ ]:
remainder=np.mod(var1,var2)
print(remainder)

[0 2 0 1]


In [ ]:
power=np.power(var1,var2)
print(power)

[ 1 16  3 64]


In [ ]:
var1=np.array([1,2,3,4],dtype='f')
print(np.reciprocal(var1))

[1.         0.5        0.33333334 0.25      ]


## 2D Array

In [ ]:
var1=np.array([[2,3,4],[1,2,3]])
var2=np.array([[1,2,3],[5,6,7]])
add=np.add(var1,var2)
print(add)

[[ 3  5  7]
 [ 6  8 10]]


In [ ]:
var1=np.array([[2,3,4],[1,2,3]])
var2=np.array([[1,2,3],[5,6,7]])
multiply=np.multiply(var1,var2)
print(multiply)

[[ 2  6 12]
 [ 5 12 21]]
