[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alok8663/Numpy/blob/main/Numpy3.ipynb)


# Numpy Arrays Functions

## Search Array

In [65]:
import numpy as np
var=np.array([4,3,2,6,7,5,8,12])
x=np.where((var%2==0))
print(x)

(array([0, 2, 3, 6, 7]),)


In [66]:
var1=np.array([1,2,3,4,6,7,8])
y=np.searchsorted(var1,5)
print(y)

4


# Sort Array

In [67]:
var=np.array([4,3,2,6,7,5,8,12])
print(np.sort(var))

[ 2  3  4  5  6  7  8 12]


In [68]:
var1=np.array([[4,2,3],[1,12,5],[22,52,6]])
print(np.sort(var1))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [69]:
var2=np.array(['a','s','d','f'])
print(np.sort(var2))

['a' 'd' 'f' 's']


# Filter Array

In [70]:
# Filter Array is getting some elements out of an existing array and creating a new array out of them.

In [71]:
var3=np.array(['a','s','d','f'])
f=[True,False,True,False]
new_a=var3[f]
print(new_a)
print(type(new_a))

['a' 'd']
<class 'numpy.ndarray'>


# Arithmetic Functions

## Shuffle

In [72]:
var1=np.array([1,2,3,4,6,7,8])
np.random.shuffle(var1)
print(var1)

[4 6 3 8 7 1 2]


## Unique

In [73]:
var4=np.array([1,2,3,2,4,2,6,7,8,2])
x=np.unique(var4,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 6, 7, 8]), array([0, 1, 2, 4, 6, 7, 8]), array([1, 4, 1, 1, 1, 1, 1]))


## Resize

In [74]:
var1=np.array([1,2,3,4,5,7])
y=np.resize(var1,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 7]]


## Flatten

In [75]:
var1=np.array([1,2,3,4,5,7])
y=np.resize(var1,(3,2))
print(y.flatten())

[1 2 3 4 5 7]


In [76]:
print(y.ravel())

[1 2 3 4 5 7]


# Insert

In [77]:
arr1=np.array([1,2,3,4])
v=np.insert(arr1,(2,4),33)
print(v)

[ 1  2 33  3  4 33]


In [78]:
arr4=np.array([1,2,3,4])
v4=np.append(arr4,7.8)
print(v4)

[1.  2.  3.  4.  7.8]


In [79]:
arr2=np.array([[1,2,3],[3,2,1]])
v1=np.insert(arr2,2,5,axis=0)
print(v1)

[[1 2 3]
 [3 2 1]
 [5 5 5]]


In [80]:
arr3=np.array([[1,2,3],[3,2,1]])
v2=np.insert(arr2,2,[7,8,9],axis=0)
print(v2)

[[1 2 3]
 [3 2 1]
 [7 8 9]]


# Delete

In [81]:
arr5=np.array([1,2,3,4])
d=np.delete(arr5,2)
print(d)

[1 2 4]


# Matrix

In [82]:
a1=np.matrix([[1,2],[4,5]])
print(a1)
print()
a3=np.matrix([[3,2],[6,5]])
print(a3)
print()
print(a1+a3)
print(type(a1))

[[1 2]
 [4 5]]

[[3 2]
 [6 5]]

[[ 4  4]
 [10 10]]
<class 'numpy.matrix'>


In [83]:
print(a1*a3)
print()
print(a1.dot(a3))

[[15 12]
 [42 33]]

[[15 12]
 [42 33]]


In [84]:
a2=np.array([[1,2,3],[4,5,6]])
a4=np.array([[3,2,1],[6,5,4]])
print(a2)
print()
print(a4)
print()
print()
print(a2*a4)
print()
print(np.multiply(a2,a4))

[[1 2 3]
 [4 5 6]]

[[3 2 1]
 [6 5 4]]


[[ 3  4  3]
 [24 25 24]]

[[ 3  4  3]
 [24 25 24]]


# Matrix Function in Numpy Arrays

## Transpose

In [85]:
c=np.matrix([[1,2,3],[4,5,6]])
print(c)
print()
print(np.transpose(c))
print()
print(c.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


## Swapaxes

In [86]:
print(np.swapaxes(c,0,1))

[[1 4]
 [2 5]
 [3 6]]


In [87]:
a1=np.matrix([[1,2],[4,5]])
print(a1)
print()
print(np.swapaxes(a1,0,1))

[[1 2]
 [4 5]]

[[1 4]
 [2 5]]


## Inverse

In [88]:
a1=np.matrix([[1,2],[4,5]])
print(a1)
print()
print(np.linalg.inv(a1))

[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


## Power

In [91]:
a1=np.matrix([[1,2],[4,5]])
print(a1)
print()
print(np.linalg.matrix_power(a1,2))

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]


In [92]:
print(np.linalg.matrix_power(a1,0))    # Here, it will print Identity Matrix

[[1 0]
 [0 1]]


In [93]:
a1=np.matrix([[1,2],[4,5]])
print(a1)
print()
print(np.linalg.det(a1))

[[1 2]
 [4 5]]

-2.9999999999999996
